name: Pluto
on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "^3.6"
      - name: Prepare python 
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          python -m poetry config virtualenvs.in-project true
          python -m poetry install
          source $(python -m poetry env info --path)/bin/activate
      - name: Run Pluto Tests
        run: |
          python -m pytest tests/
